spring:
  application:
   name: rakshithlearnSpringboot
  datasource:
    url: jdbc:postgresql://localhost:5432/vignesh
    username: vignesh
    password: vignesh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 1234

jwt:
  token:
    key: ba60c2179506a59fb32895f27a7088bd32806b6d78b3a8efe85d37bcd83f652903feba09992ef92b65033a03598cdfd3b064c2069054ca7d6a598dc69e4399be
    expiration: 30